import Head from "next/head";
import { Links } from "../components/links";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Links />
      <main>yay</main>
    </div>
  );
}
